Repository piskvorky/smart_open, pull requests merged in 2020-12, with the labels that each got.

#567 add localstack to howto
  howto.md
Labels: documentation

#569 refactor s3 submodule to minimize resource usage
  benchmark/read_s3.py
  howto.md
  setup.py
  smart_open/s3.py
Labels: enhancement, performance

#572 Fix typo in README.rst
  README.rst
Labels: documentation

#571 Change download_as_bytes to download_as_string in gcs submodule
  CHANGELOG.md
  README.rst
  smart_open/gcs.py
  smart_open/tests/test_gcs.py
Labels: enhancement

#546 Fix tests that were broken under Windows
  smart_open/tests/test_hdfs.py
  smart_open/tests/test_s3.py
Labels: hacktoberfest-accepted
